tracking_server: dummy is required
Otherwise we get:

Processing tracking_server/tracking_server.proto
Traceback (most recent call last):
  File "/home/julianoes/.local/bin/protoc-gen-mavsdk", line 8, in <module>
    sys.exit(main())
  File "/home/julianoes/.local/lib/python3.9/site-packages/protoc_gen_mavsdk/__main__.py", line 17, in main
    AutoGen.generate_reactive(request).SerializeToString())
  File "/home/julianoes/.local/lib/python3.9/site-packages/protoc_gen_mavsdk/autogen.py", line 81, in generate_reactive
    f.content = str(out_file)
  File "/home/julianoes/.local/lib/python3.9/site-packages/protoc_gen_mavsdk/autogen_file.py", line 28, in __repr__
    return self._template.render(package=self._package,
  File "/home/julianoes/.local/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/julianoes/.local/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/julianoes/.local/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/julianoes/src/MAVSDK/tools/../templates/plugin_h/file.j2", line 74, in top-level template code
    {{ indent(method, 1) }}
  File "/home/julianoes/.local/lib/python3.9/site-packages/protoc_gen_mavsdk/utils.py", line 85, in jinja_indent
    _in_str = str(_in_str)
  File "/home/julianoes/.local/lib/python3.9/site-packages/protoc_gen_mavsdk/methods.py", line 277, in __repr__
    return_type=self._return_type,
AttributeError: 'Stream' object has no attribute '_return_type'
--custom_out: protoc-gen-custom: Plugin failed with status code 1.