core: fix deprecated-copy warning in GCC 9
This fixes the warning that appeared with GCC 9:

core/system_impl.cpp:877:73: error:
implicitly-declared
‘dronecode_sdk::MAVLinkParameters::ParamValue::ParamValue(const
dronecode_sdk::MAVLinkParameters::ParamValue&)’ is deprecated
[-Werror=deprecated-copy]