src: add missing include <algorithm>
Fixes errors in the form of:
MAVSDK/src/mavsdk/core/call_every_handler.cpp:33:20: error: ‘find_if’ is not a member of ‘std’

This is with GCC 14.1.1